# Plagiarism Detection Model

Now that you've created training and test data, you are ready to define and train a model. Your goal in this notebook, will be to train a binary classification model that learns to label an answer file as either plagiarized or not, based on the features you provide the model.

This task will be broken down into a few discrete steps:

* Upload your data to S3.
* Define a binary classification model and a training script.
* Train your model and deploy it.
* Evaluate your deployed classifier and answer some questions about your approach.

To complete this notebook, you'll have to complete all given exercises and answer all the questions in this notebook.
> All your tasks will be clearly labeled **EXERCISE** and questions as **QUESTION**.

It will be up to you to explore different classification models and decide on a model that gives you the best performance for this dataset.

---

## Load Data to S3

In the last notebook, you should have created two files: a `training.csv` and `test.csv` file with the features and class labels for the given corpus of plagiarized/non-plagiarized text data. 

>The below cells load in some AWS SageMaker libraries and creates a default bucket. After creating this bucket, you can upload your locally stored data to S3.

Save your train and test `.csv` feature files, locally. To do this you can run the second notebook "2_Plagiarism_Feature_Engineering" in SageMaker or you can manually upload your files to this notebook using the upload icon in Jupyter Lab. Then you can upload local files to S3 by using `sagemaker_session.upload_data` and pointing directly to where the training data is saved.

In [2]:
import pandas as pd
import boto3
import sagemaker

In [3]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# session and role
sagemaker_session = sagemaker.Session()
role = sagemaker.get_execution_role()

# create an S3 bucket
bucket = sagemaker_session.default_bucket()

## EXERCISE: Upload your training data to S3

Specify the `data_dir` where you've saved your `train.csv` file. Decide on a descriptive `prefix` that defines where your data will be uploaded in the default S3 bucket. Finally, create a pointer to your training data by calling `sagemaker_session.upload_data` and passing in the required parameters. It may help to look at the [Session documentation](https://sagemaker.readthedocs.io/en/stable/session.html#sagemaker.session.Session.upload_data) or previous SageMaker code examples.

You are expected to upload your entire directory. Later, the training script will only access the `train.csv` file.

In [4]:
# should be the name of directory you created to save your features data
data_dir = 'plagiarism_data'

# set prefix, a descriptive name for a directory  
prefix = 'plagiarism_classification'

# upload all data to S3
#first convert to format that linear learner can use (n)
input_data = sagemaker_session.upload_data(data_dir, bucket = bucket, key_prefix = prefix)
print(input_data)

'upload_data' method will be deprecated in favor of 'S3Uploader' class (https://sagemaker.readthedocs.io/en/stable/s3.html#sagemaker.s3.S3Uploader) in SageMaker Python SDK v2.


s3://sagemaker-us-east-2-866057175451/plagiarism_classification


### Test cell

Test that your data has been successfully uploaded. The below cell prints out the items in your S3 bucket and will throw an error if it is empty. You should see the contents of your `data_dir` and perhaps some checkpoints. If you see any other files listed, then you may have some old model files that you can delete via the S3 console (though, additional files shouldn't affect the performance of model developed in this notebook).

In [5]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# confirm that data is in S3 bucket
empty_check = []
for obj in boto3.resource('s3').Bucket(bucket).objects.all():
    empty_check.append(obj.key)
    print(obj.key)

assert len(empty_check) !=0, 'S3 bucket is empty.'
print('Test passed!')

plagiarism_classification/test.csv
plagiarism_classification/train.csv
Test passed!


---

# Modeling

Now that you've uploaded your training data, it's time to define and train a model!

The type of model you create is up to you. For a binary classification task, you can choose to go one of three routes:
* Use a built-in classification algorithm, like LinearLearner.
* Define a custom Scikit-learn classifier, a comparison of models can be found [here](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html).
* Define a custom PyTorch neural network classifier. 

It will be up to you to test out a variety of models and choose the best one. Your project will be graded on the accuracy of your final model. 
 
---

## EXERCISE: Complete a training script 

To implement a custom classifier, you'll need to complete a `train.py` script. You've been given the folders `source_sklearn` and `source_pytorch` which hold starting code for a custom Scikit-learn model and a PyTorch model, respectively. Each directory has a `train.py` training script. To complete this project **you only need to complete one of these scripts**; the script that is responsible for training your final model.

A typical training script:
* Loads training data from a specified directory
* Parses any training & model hyperparameters (ex. nodes in a neural network, training epochs, etc.)
* Instantiates a model of your design, with any specified hyperparams
* Trains that model 
* Finally, saves the model so that it can be hosted/deployed, later

### Defining and training a model
Much of the training script code is provided for you. Almost all of your work will be done in the `if __name__ == '__main__':` section. To complete a `train.py` file, you will:
1. Import any extra libraries you need
2. Define any additional model training hyperparameters using `parser.add_argument`
2. Define a model in the `if __name__ == '__main__':` section
3. Train the model in that same section

Below, you can use `!pygmentize` to display an existing `train.py` file. Read through the code; all of your tasks are marked with `TODO` comments. 

**Note: If you choose to create a custom PyTorch model, you will be responsible for defining the model in the `model.py` file,** and a `predict.py` file is provided. If you choose to use Scikit-learn, you only need a `train.py` file; you may import a classifier from the `sklearn` library.

In [12]:
# directory can be changed to: source_sklearn or source_pytorch
!pygmentize source_sklearn/train.py

from __future__ import print_function

import argparse
import os
import pandas as pd

from sklearn.externals import joblib

## TODO: Import any additional libraries you need to define a model


# Provided model load function
def model_fn(model_dir):
    """Load model from the model_dir. This is the same model that is saved
    in the main if statement.
    """
    print("Loading model.")
    
    # load using joblib
    model = joblib.load(os.path.join(model_dir, "model.joblib"))
    print("Done loading model.")
    
    return model


## TODO: Complete the main code
if __name__ == '__main__':
    
    # All of the model parameters and training parameters are sent as arguments
    # when this script is executed, during a training job
    
    # Here we set up an argument parser to easily access the parameters
    parser = argparse.ArgumentParser()

    # SageMaker parameters, like the directories for training data and saving models; set automatically
    # Do not need to change
    par

### Provided code

If you read the code above, you can see that the starter code includes a few things:
* Model loading (`model_fn`) and saving code
* Getting SageMaker's default hyperparameters
* Loading the training data by name, `train.csv` and extracting the features and labels, `train_x`, and `train_y`

If you'd like to read more about model saving with [joblib for sklearn](https://scikit-learn.org/stable/modules/model_persistence.html) or with [torch.save](https://pytorch.org/tutorials/beginner/saving_loading_models.html), click on the provided links.

---
# Create an Estimator

When a custom model is constructed in SageMaker, an entry point must be specified. This is the Python file which will be executed when the model is trained; the `train.py` function you specified above. To run a custom training script in SageMaker, construct an estimator, and fill in the appropriate constructor arguments:

* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `source_sklearn` OR `source_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **role**: Role ARN, which was specified, above.
* **train_instance_count**: The number of training instances (should be left at 1).
* **train_instance_type**: The type of SageMaker instance for training. Note: Because Scikit-learn does not natively support GPU training, Sagemaker Scikit-learn does not currently support training on GPU instance types.
* **sagemaker_session**: The session used to train on Sagemaker.
* **hyperparameters** (optional): A dictionary `{'name':value, ..}` passed to the train function as hyperparameters.

Note: For a PyTorch model, there is another optional argument **framework_version**, which you can set to the latest version of PyTorch, `1.0`.

## EXERCISE: Define a Scikit-learn or PyTorch estimator

To import your desired estimator, use one of the following lines:
```
from sagemaker.sklearn.estimator import SKLearn
```
```
from sagemaker.pytorch import PyTorch
```

In [ ]:
#from sagemaker.pytorch import PyTorch

## EXERCISE: Train the estimator

Train your estimator on the training data stored in S3. This should create a training job that you can monitor in your SageMaker console.

In [31]:
#test load training data
train_data = pd.read_csv('s3://sagemaker-us-east-2-866057175451/plagiarism_classification/train.csv', header=None, names=None)

train_data_np_x = train_data.iloc[:,1:].to_numpy().astype('float32')
train_data_np_y = train_data.iloc[:,0].to_numpy().astype('float32')
formatted = estimator.record_set(train_data_np_x, labels=train_data_np_y)

In [32]:
print(train_data_np_x)

[[0.39814815 0.         0.19178082]
 [0.8693694  0.3824885  0.8464912 ]
 [0.59358287 0.06043956 0.31606218]
 [0.5445026  0.         0.24257426]
 [0.32950193 0.         0.16117217]
 [0.59030837 0.         0.30165288]
 [0.75977653 0.1954023  0.48430493]
 [0.516129   0.         0.27083334]
 [0.4408602  0.         0.22395833]
 [0.9794521  0.7446808  0.9       ]
 [0.9513889  0.4532374  0.89403975]
 [0.9764706  0.5030303  0.8232044 ]
 [0.8117647  0.23636363 0.4597701 ]
 [0.44117647 0.         0.30555555]
 [0.4888889  0.         0.2826087 ]
 [0.81395346 0.6296296  0.7888889 ]
 [0.6111111  0.         0.32467532]
 [1.         0.954023   1.        ]
 [0.6340206  0.         0.36893204]
 [0.5829384  0.05339806 0.41666666]
 [0.63793105 0.29515418 0.48987854]
 [0.42038217 0.         0.21875   ]
 [0.6877637  0.04741379 0.5163934 ]
 [0.6766467  0.08641975 0.47252747]
 [0.7692308  0.44217688 0.60645163]
 [0.7122642  0.05797102 0.53669727]
 [0.62992126 0.27309236 0.3943662 ]
 [0.71573603 0.         0.34

In [33]:
%%time
from sagemaker import LinearLearner
# Train your estimator on S3 training data
output_path = 's3://{}/{}'.format(bucket, prefix)

estimator = LinearLearner(role=role,
                          train_instance_count=1, 
                          train_instance_type='ml.c4.xlarge',
                          predictor_type='binary_classifier',
                          output_path=output_path,
                          sagemaker_session=sagemaker_session,
                          epochs=15)

estimator.fit(formatted)

'get_image_uri' method will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.
's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.
'get_image_uri' method will be deprecated in favor of 'ImageURIProvider' class in SageMaker Python SDK v2.


2020-06-09 09:18:25 Starting - Starting the training job...
2020-06-09 09:18:28 Starting - Launching requested ML instances......
2020-06-09 09:19:30 Starting - Preparing the instances for training......
2020-06-09 09:20:42 Downloading - Downloading input data...
2020-06-09 09:21:23 Training - Training image download completed. Training in progress.
2020-06-09 09:21:23 Uploading - Uploading generated training modelDocker entrypoint called with argument(s): train
Running default environment configuration script
[06/09/2020 09:21:21 INFO 140195304769344] Reading default configuration from /opt/amazon/lib/python2.7/site-packages/algorithm/resources/default-input.json: {u'loss_insensitivity': u'0.01', u'epochs': u'15', u'feature_dim': u'auto', u'init_bias': u'0.0', u'lr_scheduler_factor': u'auto', u'num_calibration_samples': u'10000000', u'accuracy_top_k': u'3', u'_num_kv_servers': u'auto', u'use_bias': u'true', u'num_point_for_scaler': u'10000', u'_log_level': u'info', u'quantile': u'0.5'

[2020-06-09 09:21:21.870] [tensorio] [info] epoch_stats={"data_pipeline": "/opt/ml/input/data/train", "epoch": 26, "duration": 28, "num_examples": 1, "num_bytes": 3920}
#metrics {"Metrics": {"train_binary_classification_cross_entropy_objective": {"count": 1, "max": 0.6105422973632812, "sum": 0.6105422973632812, "min": 0.6105422973632812}}, "EndTime": 1591694481.870316, "Dimensions": {"model": 0, "Host": "algo-1", "Operation": "training", "Algorithm": "Linear Learner", "epoch": 11}, "StartTime": 1591694481.870191}

#metrics {"Metrics": {"train_binary_classification_cross_entropy_objective": {"count": 1, "max": 0.6008611406598773, "sum": 0.6008611406598773, "min": 0.6008611406598773}}, "EndTime": 1591694481.870444, "Dimensions": {"model": 1, "Host": "algo-1", "Operation": "training", "Algorithm": "Linear Learner", "epoch": 11}, "StartTime": 1591694481.870422}

#metrics {"Metrics": {"train_binary_classification_cross_entropy_objective": {"count": 1, "max": 0.6550847189767021, "sum": 0.655


2020-06-09 09:21:30 Completed - Training job completed
Training seconds: 48
Billable seconds: 48
CPU times: user 526 ms, sys: 61.9 ms, total: 588 ms
Wall time: 3min 42s


## EXERCISE: Deploy the trained model

After training, deploy your model to create a `predictor`. If you're using a PyTorch model, you'll need to create a trained `PyTorchModel` that accepts the trained `<model>.model_data` as an input parameter and points to the provided `source_pytorch/predict.py` file as an entry point. 

To deploy a trained model, you'll use `<model>.deploy`, which takes in two arguments:
* **initial_instance_count**: The number of deployed instances (1).
* **instance_type**: The type of SageMaker instance for deployment.

Note: If you run into an instance error, it may be because you chose the wrong training or deployment instance_type. It may help to refer to your previous exercise code to see which types of instances we used.

In [34]:
%%time

# uncomment, if needed
# from sagemaker.pytorch import PyTorchModel


# deploy your model to create a predictor
predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.t2.medium')


Parameter image will be renamed to image_uri in SageMaker Python SDK v2.


---------------!CPU times: user 273 ms, sys: 9.84 ms, total: 283 ms
Wall time: 7min 31s


---
# Evaluating Your Model

Once your model is deployed, you can see how it performs when applied to our test data.

The provided cell below, reads in the test data, assuming it is stored locally in `data_dir` and named `test.csv`. The labels and features are extracted from the `.csv` file.

In [69]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import os

# read in test data, assuming it is stored locally
test_data = pd.read_csv(os.path.join(data_dir, "test.csv"), header=None, names=None)

# labels are in the first column
test_y = test_data.iloc[:,0]
test_x = test_data.iloc[:,1:]

## EXERCISE: Determine the accuracy of your model

Use your deployed `predictor` to generate predicted, class labels for the test data. Compare those to the *true* labels, `test_y`, and calculate the accuracy as a value between 0 and 1.0 that indicates the fraction of test data that your model classified correctly. You may use [sklearn.metrics](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) for this calculation.

**To pass this project, your model should get at least 90% test accuracy.**

In [85]:
import numpy as np
# First: generate predicted, class labels
test_y_np = test_y.to_numpy().astype('float32')
test_x_np = test_x.to_numpy().astype('float32')

test_y_preds = []
for i in test_x_np:
    result = predictor.predict(i)
    test_y_preds += [x.label['predicted_label'].float32_tensor.values[0] for x in result]
test_y_preds = np.array(test_y_preds).astype(int)

"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test that your model generates the correct number of labels
assert len(test_y_preds)==len(test_y), 'Unexpected number of predictions.'
print('Test passed!')

Test passed!


In [86]:
from sklearn.metrics import accuracy_score
# Second: calculate the test accuracy
accuracy = accuracy_score(test_y, test_y_preds)

print(accuracy)


## print out the array of predicted and true labels, if you want
print('\nPredicted class labels: ')
print(test_y_preds)
print('\nTrue class labels: ')
print(test_y.values)

0.96

Predicted class labels: 
[1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1 0 0]

True class labels: 
[1 1 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 0]


In [87]:

# calculate true positives, false positives, true negatives, false negatives
fp = np.logical_and(1-test_y_np, test_y_preds).sum()
fn = np.logical_and(test_y_np, 1-test_y_preds).sum()
#print results
print('\nFalse Positives: ')
print(fp)
print('\nFalse Negatives: ')
print(fn)


False Positives: 
1

False Negatives: 
0


### Question 1: How many false positives and false negatives did your model produce, if any? And why do you think this is?

** Answer**: 
My model produces one false positive and no false negatives. I believe that this is the case because the use of words is a great predictor for plagiarism and therefore it is easy to recognize plagiarism based on the used metrics. This implies that when the same words are used, the chance that it is plagiarism is very high. On the other hand when there is no plagiarism it is really unlikely that the words used are very similar. This is why there are no false negatives because if the words are similar it is really likely that it is plagiarism. On the other hand false positives might occur if a description just by chance, as it is much more likely to accidentally consider something plagiarism than to miss a case of plagiarism

### Question 2: How did you decide on the type of model to use? 

** Answer**:
I decided to first try using a pytorch model and quickly realized that it the task does not really warrant the use of such a complex algorithm. In essence the problem is fairly simple considering that each sample only has 3 datapoints to decide whether it is plagiarism or not. Therefore, I next tried the simplest model I could think of, which was the Sagemaker built in Linear Learner. Since it worked well I stuck with it.


----
## EXERCISE: Clean up Resources

After you're done evaluating your model, **delete your model endpoint**. You can do this with a call to `.delete_endpoint()`. You need to show, in this notebook, that the endpoint was deleted. Any other resources, you may delete from the AWS console, and you will find more instructions on cleaning up all your resources, below.

In [88]:
# uncomment and fill in the line below!
predictor.delete_endpoint()


### Deleting S3 bucket

When you are *completely* done with training and testing models, you can also delete your entire S3 bucket. If you do this before you are done training your model, you'll have to recreate your S3 bucket and upload your training data again.

In [89]:
# deleting bucket, uncomment lines below

bucket_to_delete = boto3.resource('s3').Bucket(bucket)
bucket_to_delete.objects.all().delete()

[{'ResponseMetadata': {'RequestId': 'E7B228DEBCBE5B66',
   'HostId': 'Y8Dsrqxu/NX2iOnTB24B9urzLx8ka+egHCqthQ2eRzTTJZXlZrEfFQzPE0+X2BoYsKfYCiXjaq0=',
   'HTTPStatusCode': 200,
   'HTTPHeaders': {'x-amz-id-2': 'Y8Dsrqxu/NX2iOnTB24B9urzLx8ka+egHCqthQ2eRzTTJZXlZrEfFQzPE0+X2BoYsKfYCiXjaq0=',
    'x-amz-request-id': 'E7B228DEBCBE5B66',
    'date': 'Tue, 09 Jun 2020 09:57:44 GMT',
    'connection': 'close',
    'content-type': 'application/xml',
    'transfer-encoding': 'chunked',
    'server': 'AmazonS3'},
   'RetryAttempts': 0},
  'Deleted': [{'Key': 'plagiarism_classification/linear-learner-2020-06-09-08-57-44-045/output/model.tar.gz'},
   {'Key': 'sagemaker-record-sets/LinearLearner-2020-06-09-09-17-17-855/.amazon.manifest'},
   {'Key': 'plagiarism_classification/train.csv'},
   {'Key': 'sagemaker-record-sets/LinearLearner-2020-06-09-08-57-20-086/.amazon.manifest'},
   {'Key': 'plagiarism_classification/linear-learner-2020-06-09-09-18-25-728/output/model.tar.gz'},
   {'Key': 'sagemaker-re

### Deleting all your models and instances

When you are _completely_ done with this project and do **not** ever want to revisit this notebook, you can choose to delete all of your SageMaker notebook instances and models by following [these instructions](https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-cleanup.html). Before you delete this notebook instance, I recommend at least downloading a copy and saving it, locally.

---
## Further Directions

There are many ways to improve or add on to this project to expand your learning or make this more of a unique project for you. A few ideas are listed below:
* Train a classifier to predict the *category* (1-3) of plagiarism and not just plagiarized (1) or not (0).
* Utilize a different and larger dataset to see if this model can be extended to other types of plagiarism.
* Use language or character-level analysis to find different (and more) similarity features.
* Write a complete pipeline function that accepts a source text and submitted text file, and classifies the submitted text as plagiarized or not.
* Use API Gateway and a lambda function to deploy your model to a web application.

These are all just options for extending your work. If you've completed all the exercises in this notebook, you've completed a real-world application, and can proceed to submit your project. Great job!